version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"

  # Terraform modules
  - package-ecosystem: "terraform"
    directory: "/infra/terraform/environments/poc"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"

  # Docker
  - package-ecosystem: "docker"
    directory: "/infra/grafana"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"
