apiVersion: 1

datasources:
  # Amazon Managed Prometheus
  - name: Amazon Managed Prometheus
    type: prometheus
    access: proxy
    url: ${AMP_ENDPOINT}
    isDefault: true
    jsonData:
      httpMethod: POST
      sigV4Auth: true
      sigV4AuthType: default
      sigV4Region: ${AWS_REGION}
    editable: true

  # CloudWatch
  - name: CloudWatch
    type: cloudwatch
    access: proxy
    jsonData:
      authType: default
      defaultRegion: ${AWS_REGION}
    editable: true
