apiVersion: 1

datasources:
  # Amazon Managed Prometheus
  - name: Amazon Managed Prometheus
    type: prometheus
    access: proxy
    url: ${AMP_ENDPOINT}
    isDefault: true
    jsonData:
      httpMethod: POST
      sigV4Auth: true
      sigV4AuthType: default
      sigV4Region: ${AWS_REGION}
    editable: true

  # CloudWatch
  - name: CloudWatch
    type: cloudwatch
    access: proxy
    jsonData:
      authType: default
      defaultRegion: ${AWS_REGION}
    editable: true

  # Kong Metrics (via Victoria Metrics)
  - name: Kong Metrics
    type: prometheus
    access: proxy
    url: http://kong-llm-gateway-poc-1159371345.us-west-1.elb.amazonaws.com:9090
    isDefault: false
    jsonData:
      httpMethod: POST
      timeInterval: "15s"
    editable: true
